name: 'medallion_ecommerce'
version: '1.0.0'
config-version: 2

profile: 'medallion'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

models:
  medallion_ecommerce:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
