version: 2

models:
  - name: gold_customer_360
    description: "Comprehensive customer view with LTV and behavioral metrics"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: ltv_tier
        description: "Customer lifetime value tier"
        tests:
          - accepted_values:
              values: ['platinum', 'gold', 'silver', 'bronze']
      - name: total_revenue
        description: "Lifetime total revenue"
        tests:
          - not_null
      - name: total_orders
        description: "Lifetime order count"
        tests:
          - not_null

  - name: gold_daily_revenue
    description: "Daily revenue aggregates with rolling averages"
    columns:
      - name: order_date
        description: "Calendar date"
        tests:
          - unique
          - not_null
      - name: total_revenue
        tests:
          - not_null
      - name: order_count
        tests:
          - not_null

  - name: gold_product_performance
    description: "Product-level revenue, margin, and buyer analysis"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: category
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
      - name: units_sold
        tests:
          - not_null
